// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYDn3It-ydjq8zlgLhmGC7jsChJI-GN-o',
    appId: '1:377630828131:web:d984382ee1036628a4fa56',
    messagingSenderId: '377630828131',
    projectId: 'smartfarm-7f8c0',
    authDomain: 'smartfarm-7f8c0.firebaseapp.com',
    databaseURL: 'https://smartfarm-7f8c0-default-rtdb.firebaseio.com',
    storageBucket: 'smartfarm-7f8c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5xJ824aT87SemTEG27ucTLLz5RbDjYl8',
    appId: '1:377630828131:android:0af2329aae5777d3a4fa56',
    messagingSenderId: '377630828131',
    projectId: 'smartfarm-7f8c0',
    databaseURL: 'https://smartfarm-7f8c0-default-rtdb.firebaseio.com',
    storageBucket: 'smartfarm-7f8c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4rqPew9eApVDyH-X4_P7psd83m1dTO6Y',
    appId: '1:377630828131:ios:7cd8212804b87e2ca4fa56',
    messagingSenderId: '377630828131',
    projectId: 'smartfarm-7f8c0',
    databaseURL: 'https://smartfarm-7f8c0-default-rtdb.firebaseio.com',
    storageBucket: 'smartfarm-7f8c0.appspot.com',
    iosClientId: '377630828131-587rcpmqpt87ihf9hnvku68ra7gvgdlh.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartFarmApp',
  );
}
